{% set name = "outcome" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 588ef4dc10b64e8df160d8d1310c44e1927129a66d6d2ef86845cef512c5f24c

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - attrs  >=19.2.0

test:
  imports:
    - outcome

about:
  home: https://github.com/python-trio/outcome
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Capture the outcome of Python function calls.
  description: Capture the outcome of Python function calls.

extra:
  recipe-maintainers:
    - nicoddemus
